---
title: "Store Map"
output: html_document
---
## Required libraries
```{r setup, message=FALSE}
library(readr)
library("tidyverse")
library(lubridate)
library(leaflet)
```

## Reading location data
```{r}
Locations = read_csv("FoodstuffsLocations.csv",show_col_types=FALSE)
head(Locations)
```

## Plotting location of stores on map
```{r}
factpal <- colorFactor(topo.colors(4), Locations$Type)
leaflet() %>% addTiles() %>% addCircleMarkers(data=Locations, lng=~Long, lat=~Lat, popup=~Supermarket, color=~factpal(Type))
```

## Reading distance data
```{r}
Distances = read_csv("FoodstuffsDistances.csv", show_col_types=FALSE)
head(Distances)
```
## Pivoting distance data
```{r}
Distances = Distances %>% 
  pivot_longer(-c("...1"), names_to="To", values_to="Distance") %>% 
  rename(From=...1) %>%
  mutate(Distance=Distance/1000)
head(Distances)
```
## Reading duration data
```{r}
Durations = read_csv("FoodstuffsDurations.csv", show_col_types=FALSE)
head(Durations)
```
## Pivoting duration data
```{r}
Durations = Durations %>% 
  pivot_longer(-c("...1"), names_to="To", values_to="Duration") %>%
  rename(From=...1) %>%
  mutate(Duration=Duration/60)
head(Durations)
```
## Merging distance and duration data
```{r}
Joined = right_join(Distances, Durations, by=c("From", "To"))
head(Joined)
```
## Plotting travel distance vs duration
```{r}
Joined %>% ggplot() + 
  geom_point(aes(x=Distance, y=Duration, color="red", alpha=0.1)) +
  labs(title="Distance vs Duration of each trip") +
  xlab("Distance (km)") + 
  ylab("Duration (min)") + 
  guides(color="none", alpha="none")
```
## Writing data to csv file
```{r}
write.csv(Joined, "TravelCosts.csv", row.names=FALSE)
```

